---
- :sip_stack_name: opensips_1_10
  :file_name: //home/jinguodong/workspace/sip_stack_analyze_dir/analyze_tool/opensips_1_10/modules/carrierroute/route_config.c
  :function_list: ! '["conf_error", "load_config", "parse_config", "save_config",
    "backup_config", "save_route_data_recursor"]'
  :file_headers: ! '["../../mem/shm_mem.h", "../../mem/mem.h", "../../ut.h", "route_config.h",
    "route.h", "carrierroute.h", "carrier_tree.h"]'
  :file_base_path: /home/jinguodong/workspace/sip_stack_analyze_dir/analyze_tool/opensips_1_10/modules/carrierroute/
