---
- :sip_stack_name: opensips_1_10
  :file_name: /home/jinguodong/workspace/sip_stack_analyze_dir/analyze_tool/opensips_1_10/modules/permissions/parse_config.c
  :function_list: ! '["parse_config_file", "parse_config_line", "parse_expression",
    "parse_expression_list"]'
  :file_headers: ! '["../../sr_module.h", "rule.h", "parse_config.h"]'
  :file_base_path: /home/jinguodong/workspace/sip_stack_analyze_dir/analyze_tool/opensips_1_10/modules/permissions/
